### ISSUE TITLE
Credit card ranking

### ISSUE THREAD

**Issue by mgurevin** [cisco/libfnr#13]
Hi, do you have an example for credit card ranking?

**Comment by sashank** [comment]
Am assuming you are asking about , rank and de-rank functions needed to preserve the format ? If yes , we don't have published example , but it is very trivial and could be found here http://botan.randombit.net/manual/fpe.html

**Comment by mgurevin** [comment]
Ok, I reviewed Botan sample.

Botan encrypt method;
`BigInt FPE::fe1_encrypt(const BigInt &n, const BigInt &X, const SymmetricKey &key, const std::vector<byte> &tweak)`

X and N parameter explanation;
Encrypts the value X modulo the value n using the key and tweak specified. **Returns an integer less than n.**

The FRN library does no provide upper bounds for encrypted value. Do you have a trick?

**Comment by sashank** [comment]
In FNR  no separate upper bound is taken as parameter. you may have to cycle-walk a bit if the value is above or below the range. 

Try the same luhn_check sum methods given on botan page  and define 

```
typedef struct _creditCard{
    uint64_t number:50;
}creditCard;
```

and use it this way 
`
FNR_encrypt(key, &tweak, &raw_cc, &encrypted_cc);`

and put the above in a while loop with a check

`while((encrypted_cc.number < 100000000000000) || (encrypted_cc.number >= 1000000000000000));`

the above step is cycle walking. The probability that the above hits would be very less . Remember the credit card number needs approximately 48 bits and we have declared above is 50 bits. so with negligible probability , we may need to re try encrypting if the ciphertext is out of range.

Hope this helps .

**Comment by mgurevin** [comment]
Hi again, cycle walking works fine.

Thank you sashank.
