### ISSUE TITLE
Java implementation

### ISSUE THREAD

**Issue by mgurevin** [cisco/libfnr#9]
Hello, I have been porting reference implementation to pure java. https://github.com/octabase/fnr-java

**Comment by sashank** [comment]
Hey thanks for letting us know about your project. Can we know possible applications ? or is it side fun project ?

**Comment by mgurevin** [comment]
Our company develops a new database as a service. It has rich field types like IP, Credit Card. We planning to use for lightweight encryption for some data types on client side(JS, Android, IOS or the ARM Native for IoT.).

**Comment by sashank** [comment]
Very cool, is it already in production ?

**Comment by mgurevin** [comment]
Not yet, the product still under development.

**Comment by sashank** [comment]
Do you have any updates on this ? is your usage in production ? any references ?

**Comment by mgurevin** [comment]
Hi Sashank, our retail application services (includes payment gateways) used in the production this library since March 2016. I'm sorry for reference link, customer information is confidental.

**Comment by sashank** [comment]
Thanks for the update . Np
